apiVersion: v1
kind: Secret
metadata:
  name: demo-superuser
  namespace: k8ssandra-dc1
data:
  password: dDBwLVNlY3JldA==
  username: dGVzdC1zdXBlcnVzZXI=
type: Opaque
---
apiVersion: cassandra.datastax.com/v1beta1
kind: CassandraDatacenter
metadata:
  name: dc1
  namespace: k8ssandra-dc1
spec:
  clusterName: mixed-workload
  serverType: dse
  serverVersion: 6.8.26
  size: 1
  storageConfig:
    cassandraDataVolumeClaimSpec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi
  superuserSecretName: demo-superuser
  config:
    # cassandra-yaml:
      # authenticator: com.datastax.bdp.cassandra.auth.DseAuthentsysteicator    
      # authorizer: com.datastax.bdp.cassandra.auth.DseAuthorizer
      # role_manager: com.datastax.bdp.cassandra.auth.DseRoleManager
      # endpoint_snitch: GossipingPropertyFileSnitch
      # seed_provider:
      #   - seeds: mixed-workload-seed-service,mixed-workload-dc1-additional-seed-service
      # DSE not using same authenticator as Apache Cassandra !
      # : DSE 6.8 is built on Apache Cassandra 3.11 but includes additional features and optimizations not present in the open-source version. These differences can lead to compatibility issues when trying to run a mixed cluster.
    jvm-server-options:
      initial_heap_size: 1G
      max_heap_size: 1G
