global:
  # -- Determines whether k8ssandra-operator only watch and manages
  # K8ssandraCluster in the same namespace in which the operator is deployed
  # or if watches and manages K8ssandraClusters across all namespaces.
  clusterScoped: false

# -- Determines if the k8ssandra-operator should be installed as the control plane
# or if it's simply in a secondary cluster waiting to be promoted
controlPlane: true  

# -- Allows managing CRD upgrades externally and fully disable the CRD upgrader job hook
disableCrdUpgraderJob: false
# -- Allows disabling the check for the presence of cert-manager.
cass-operator:
  disableCertManagerCheck: false